version: '3.8'

services:
  frontend:
    build: ./frontend/utlansapp
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/utlansapp:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000 

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - ./backend.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REACT_APP_API_URL=http://backend:4000

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - mariadb-data:/var/lib/mysql
    env_file:
      - ./infodb.env
      
volumes:
  mariadb-data:
